apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-manager-deployment
  labels:
    app: pod-manager
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: pod-manager
  template:
    metadata:
      labels:
        app: pod-manager
    spec:
      containers:
      - name: pod-manager
        image: ashishmahendra/jac-pod-manager:latest 
        ports:
        - containerPort: 8000 
---
apiVersion: v1
kind: Service
metadata:
  name: pod-manager-service
spec:
  selector:
    app: pod-manager
  ports:
    - protocol: TCP
      port: 8000 
      targetPort: 8000  
  type: LoadBalancer  